<a href="https://colab.research.google.com/github/aggarwal-navya/DeepLearning/blob/main/ANN_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
df= pd.read_csv("/content/DateFruit_Dataset.csv")
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [5]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [6]:
df.shape

(898, 35)

In [7]:
X= df.drop("Class", axis=1)
y= df["Class"]

In [8]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [9]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

le= LabelEncoder()
y= le.fit_transform(y)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
scaler= StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [13]:
X_train_tensor= torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor= torch.tensor(y_train, dtype=torch.long)

X_test_tensor= torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor= torch.tensor(y_test, dtype=torch.long)

In [14]:
train_dataset= TensorDataset(X_train_tensor, y_train_tensor)
test_dataset= TensorDataset(X_test_tensor, y_test_tensor)

In [15]:
train_loader= DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader= DataLoader(test_dataset, batch_size=32, shuffle=False)

In [16]:
#build model
class ANN(nn.Module):
  def __init__(self):
    super(ANN, self).__init__()
    self.model = nn.Sequential(
        nn.Linear(X.shape[1], 64),
        nn.ReLU(),
        nn.Linear(64, 64),
        nn.ReLU(),
        nn.Linear(64, 7)
    )

  def forward(self, x):
    return self.model(x)

In [18]:
model= ANN()
criteria = nn.CrossEntropyLoss()
optimizer= optim.Adam(model.parameters())

In [20]:
#training

epochs= 100
for epoch in range(epochs):
  model.train()

  running_loss = 0.0
  for xb, yb in train_dataset:
    optimizer.zero_grad()

    outputs= model(xb)
    loss= criteria(outputs, yb)
    loss.backward()
    optimizer.step()

    running_loss += loss.item()
  train_loss = running_loss / len(train_loader)
  print(f"Epoch {epoch+1}/{epochs}, Train Loss: {train_loss:.4f}")

Epoch 1/100, Train Loss: 22.0190
Epoch 2/100, Train Loss: 11.0541
Epoch 3/100, Train Loss: 8.5892
Epoch 4/100, Train Loss: 7.2811
Epoch 5/100, Train Loss: 6.4115
Epoch 6/100, Train Loss: 5.8145
Epoch 7/100, Train Loss: 5.2870
Epoch 8/100, Train Loss: 4.8917
Epoch 9/100, Train Loss: 4.4878
Epoch 10/100, Train Loss: 4.1635
Epoch 11/100, Train Loss: 3.8725
Epoch 12/100, Train Loss: 3.5972
Epoch 13/100, Train Loss: 3.5049
Epoch 14/100, Train Loss: 3.2361
Epoch 15/100, Train Loss: 2.9153
Epoch 16/100, Train Loss: 2.6321
Epoch 17/100, Train Loss: 2.5359
Epoch 18/100, Train Loss: 2.7501
Epoch 19/100, Train Loss: 2.4226
Epoch 20/100, Train Loss: 1.9737
Epoch 21/100, Train Loss: 1.9353
Epoch 22/100, Train Loss: 1.9088
Epoch 23/100, Train Loss: 1.5151
Epoch 24/100, Train Loss: 1.2251
Epoch 25/100, Train Loss: 2.1819
Epoch 26/100, Train Loss: 1.8325
Epoch 27/100, Train Loss: 1.6129
Epoch 28/100, Train Loss: 1.3889
Epoch 29/100, Train Loss: 0.7460
Epoch 30/100, Train Loss: 0.8194
Epoch 31/100, Train Loss: 2.7587
Epoch 32/100, Train Loss: 1.6241
Epoch 33/100, Train Loss: 1.3069
Epoch 34/100, Train Loss: 0.6696
Epoch 35/100, Train Loss: 0.7670
Epoch 36/100, Train Loss: 0.5408
Epoch 37/100, Train Loss: 0.7318
Epoch 38/100, Train Loss: 0.6668
Epoch 39/100, Train Loss: 0.6082
Epoch 40/100, Train Loss: 0.5787
Epoch 41/100, Train Loss: 1.8860
Epoch 42/100, Train Loss: 2.2964
Epoch 43/100, Train Loss: 1.3314
Epoch 44/100, Train Loss: 0.3597
Epoch 45/100, Train Loss: 0.2290
Epoch 46/100, Train Loss: 0.2192
Epoch 47/100, Train Loss: 0.2177
Epoch 48/100, Train Loss: 0.7009
Epoch 49/100, Train Loss: 0.7738
Epoch 50/100, Train Loss: 1.7916
Epoch 51/100, Train Loss: 1.0593
Epoch 52/100, Train Loss: 0.3649
Epoch 53/100, Train Loss: 0.1725
Epoch 54/100, Train Loss: 0.1191
Epoch 55/100, Train Loss: 0.8307
Epoch 56/100, Train Loss: 1.8638
Epoch 57/100, Train Loss: 2.1875
Epoch 58/100, Train Loss: 0.3336
Epoch 59/100, Train Loss: 0.1060
Epoch 60/100, Train Loss: 0.0693
Epoch 61/100, Train Loss: 0.2441
Epoch 62/100, Train Loss: 3.9007
Epoch 63/100, Train Loss: 0.3604
Epoch 64/100, Train Loss: 0.1310
Epoch 65/100, Train Loss: 0.0634
Epoch 66/100, Train Loss: 0.0497
Epoch 67/100, Train Loss: 0.0792
Epoch 68/100, Train Loss: 2.2905
Epoch 69/100, Train Loss: 2.1622
Epoch 70/100, Train Loss: 0.5427
Epoch 71/100, Train Loss: 1.4345
Epoch 72/100, Train Loss: 0.1183
Epoch 73/100, Train Loss: 0.0500
Epoch 74/100, Train Loss: 0.0344
Epoch 75/100, Train Loss: 0.0371
Epoch 76/100, Train Loss: 0.0278
Epoch 77/100, Train Loss: 0.5477
Epoch 78/100, Train Loss: 2.4287
Epoch 79/100, Train Loss: 0.0894
Epoch 80/100, Train Loss: 0.3323
Epoch 81/100, Train Loss: 0.4939
Epoch 82/100, Train Loss: 3.0489
Epoch 83/100, Train Loss: 0.2751
Epoch 84/100, Train Loss: 0.0576
Epoch 85/100, Train Loss: 0.0287
Epoch 86/100, Train Loss: 0.0158
Epoch 87/100, Train Loss: 0.0132
Epoch 88/100, Train Loss: 0.0112
Epoch 89/100, Train Loss: 0.0107
Epoch 90/100, Train Loss: 0.2448
Epoch 91/100, Train Loss: 4.3382
Epoch 92/100, Train Loss: 0.3630
Epoch 93/100, Train Loss: 0.1998
Epoch 94/100, Train Loss: 0.0357
Epoch 95/100, Train Loss: 0.0233
Epoch 96/100, Train Loss: 0.0172
Epoch 97/100, Train Loss: 0.0102
Epoch 98/100, Train Loss: 0.0089
Epoch 99/100, Train Loss: 0.0070
Epoch 100/100, Train Loss: 0.0068

In [23]:
# evaluation

model.eval()
total=0
correct=0

with torch.no_grad():
  for xb, yb in test_loader:
    outputs= model(xb)
    _, predicted= torch.max(outputs, 1)
    total += yb.size(0)
    correct += (predicted == yb).sum().item()
print("total values", total)
print("correct value", correct)
print("accuracy", correct/total * 100)

total values 180
correct value 163
accuracy 90.55555555555556

In [28]:
from sklearn.decomposition import PCA

pca= PCA(n_components=0.95)
X_train_pca= pca.fit_transform(X_train_scaled)
X_test_pca= pca.transform(X_test_scaled)

In [30]:
X_train_pca_tensor= torch.tensor(X_train_pca, dtype=torch.float32)
X_test_pca_tensor= torch.tensor(X_test_pca, dtype=torch.float32)

In [33]:
train_pca_dataset = TensorDataset(X_train_pca_tensor, y_train_tensor)
test_pca_dataset= TensorDataset(X_test_pca_tensor, y_test_tensor)

In [34]:
train_pca_loader = DataLoader(train_pca_dataset, batch_size=32, shuffle=True)
test_pca_loader= DataLoader(test_pca_dataset, batch_size=32, shuffle=True)

In [35]:
class ANN_PCA(nn.Module):
  def __init__(self):
    super(ANN_PCA, self).__init__()
    self.model= nn.Sequential(
        nn.Linear(X_train_pca.shape[1], 64),
        nn.ReLU(),
        nn.Linear(64, 64),
        nn.ReLU(),
        nn.Linear(64,7)
    )
  def forward(self, x):
    return self.model(x)

model_pca= ANN_PCA()

criteria_pca= nn.CrossEntropyLoss()
optimizer_pca= optim.Adam(model_pca.parameters())

In [37]:
epochs= 100
for epoch in range(epochs):
  model_pca.train()

  running_loss= 0.0
  for xb, yb in train_pca_loader:
    optimizer_pca.zero_grad()

    outputs= model_pca(xb)
    loss= criteria_pca(outputs, yb)
    loss.backward()
    optimizer_pca.step()

    running_loss += loss.item()
  train_loss= running_loss / len(train_pca_loader)
  print(f"Epoch {epoch+1}/{epochs}, Train Loss: {train_loss:.4f}")

Epoch 1/100, Train Loss: 1.6041
Epoch 2/100, Train Loss: 1.0578
Epoch 3/100, Train Loss: 0.7278
Epoch 4/100, Train Loss: 0.5571
Epoch 5/100, Train Loss: 0.4487
Epoch 6/100, Train Loss: 0.3959
Epoch 7/100, Train Loss: 0.3743
Epoch 8/100, Train Loss: 0.3237
Epoch 9/100, Train Loss: 0.3108
Epoch 10/100, Train Loss: 0.2906
Epoch 11/100, Train Loss: 0.2834
Epoch 12/100, Train Loss: 0.2593
Epoch 13/100, Train Loss: 0.2506
Epoch 14/100, Train Loss: 0.2528
Epoch 15/100, Train Loss: 0.2359
Epoch 16/100, Train Loss: 0.2194
Epoch 17/100, Train Loss: 0.2108
Epoch 18/100, Train Loss: 0.2143
Epoch 19/100, Train Loss: 0.2073
Epoch 20/100, Train Loss: 0.1951
Epoch 21/100, Train Loss: 0.1952
Epoch 22/100, Train Loss: 0.1849
Epoch 23/100, Train Loss: 0.1932
Epoch 24/100, Train Loss: 0.1806
Epoch 25/100, Train Loss: 0.1797
Epoch 26/100, Train Loss: 0.1728
Epoch 27/100, Train Loss: 0.1680
Epoch 28/100, Train Loss: 0.1720
Epoch 29/100, Train Loss: 0.1727
Epoch 30/100, Train Loss: 0.1678
Epoch 31/100, Train Loss: 0.1624
Epoch 32/100, Train Loss: 0.1525
Epoch 33/100, Train Loss: 0.1526
Epoch 34/100, Train Loss: 0.1556
Epoch 35/100, Train Loss: 0.1495
Epoch 36/100, Train Loss: 0.1456
Epoch 37/100, Train Loss: 0.1485
Epoch 38/100, Train Loss: 0.1484
Epoch 39/100, Train Loss: 0.1484
Epoch 40/100, Train Loss: 0.1512
Epoch 41/100, Train Loss: 0.1502
Epoch 42/100, Train Loss: 0.1360
Epoch 43/100, Train Loss: 0.1349
Epoch 44/100, Train Loss: 0.1379
Epoch 45/100, Train Loss: 0.1279
Epoch 46/100, Train Loss: 0.1294
Epoch 47/100, Train Loss: 0.1249
Epoch 48/100, Train Loss: 0.1258
Epoch 49/100, Train Loss: 0.1277
Epoch 50/100, Train Loss: 0.1246
Epoch 51/100, Train Loss: 0.1265
Epoch 52/100, Train Loss: 0.1250
Epoch 53/100, Train Loss: 0.1164
Epoch 54/100, Train Loss: 0.1133
Epoch 55/100, Train Loss: 0.1133
Epoch 56/100, Train Loss: 0.1159
Epoch 57/100, Train Loss: 0.1088
Epoch 58/100, Train Loss: 0.1084
Epoch 59/100, Train Loss: 0.1098
Epoch 60/100, Train Loss: 0.1101
Epoch 61/100, Train Loss: 0.1087
Epoch 62/100, Train Loss: 0.1085
Epoch 63/100, Train Loss: 0.1159
Epoch 64/100, Train Loss: 0.1106
Epoch 65/100, Train Loss: 0.1069
Epoch 66/100, Train Loss: 0.0998
Epoch 67/100, Train Loss: 0.1008
Epoch 68/100, Train Loss: 0.0985
Epoch 69/100, Train Loss: 0.0967
Epoch 70/100, Train Loss: 0.0943
Epoch 71/100, Train Loss: 0.0949
Epoch 72/100, Train Loss: 0.0938
Epoch 73/100, Train Loss: 0.0932
Epoch 74/100, Train Loss: 0.0945
Epoch 75/100, Train Loss: 0.0928
Epoch 76/100, Train Loss: 0.0890
Epoch 77/100, Train Loss: 0.0910
Epoch 78/100, Train Loss: 0.0906
Epoch 79/100, Train Loss: 0.0834
Epoch 80/100, Train Loss: 0.0854
Epoch 81/100, Train Loss: 0.0852
Epoch 82/100, Train Loss: 0.0825
Epoch 83/100, Train Loss: 0.0852
Epoch 84/100, Train Loss: 0.0817
Epoch 85/100, Train Loss: 0.0848
Epoch 86/100, Train Loss: 0.0797
Epoch 87/100, Train Loss: 0.0784
Epoch 88/100, Train Loss: 0.0788
Epoch 89/100, Train Loss: 0.0782
Epoch 90/100, Train Loss: 0.0797
Epoch 91/100, Train Loss: 0.0694
Epoch 92/100, Train Loss: 0.0753
Epoch 93/100, Train Loss: 0.0707
Epoch 94/100, Train Loss: 0.0696
Epoch 95/100, Train Loss: 0.0770
Epoch 96/100, Train Loss: 0.0702
Epoch 97/100, Train Loss: 0.0664
Epoch 98/100, Train Loss: 0.0651
Epoch 99/100, Train Loss: 0.0749
Epoch 100/100, Train Loss: 0.0650

In [40]:
model.eval()
total_pca=0
correct_pca=0

with torch.no_grad():
  for xb, yb in test_loader:
    outputs= model(xb)
    _, predicted= torch.max(outputs, 1)
    total_pca += yb.size(0)
    correct_pca +=(predicted == yb).sum().item()
print("total_pca", total_pca)
print("correct_pca", correct_pca)
print("accuracy", correct_pca/total_pca * 100)

total_pca 180
correct_pca 163
accuracy 90.55555555555556